# Generated by Django 3.1.7 on 2021-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caducidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('vida_prod', models.CharField(help_text='Tiempo de vida del producto', max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Caducidades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Decoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('decoracion', models.CharField(help_text='Descripción de la decoración', max_length=30, unique=True)),
                ('estilo', models.CharField(help_text='descripcion del estilo', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='decoracion/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Decoraciones',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre de la Oferta', max_length=30, unique=True)),
                ('precioOferta', models.FloatField(default=0)),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('existencia', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('sabor', models.CharField(help_text='Descripción del Sabor', max_length=30, unique=True)),
                ('descripcion', models.CharField(help_text='observaciones', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sabores',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Sub-Categoría', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Unidad de Medida', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidad de medidas',
            },
        ),
    ]
