# Generated by Django 3.1.7 on 2021-03-03 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_unidadmedida_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_unidadmedida_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.categoria'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_subcategoria_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_subcategoria_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sabor',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sabor_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sabor',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sabor_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='caducidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.caducidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='decoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.decoracion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.ManyToManyField(to='inv.Oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.sabor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_producto_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_producto_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.unidadmedida'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_oferta_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_oferta_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marca',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_marca_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marca',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_marca_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decoracion',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_decoracion_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decoracion',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_decoracion_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_categoria_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_categoria_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caducidad',
            name='u_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_caducidad_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caducidad',
            name='u_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_caducidad_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'descripcion')},
        ),
    ]
